### ISSUE TITLE
De kleuren kloppen nog niet helemaal

### ISSUE THREAD

**Issue by eelcoh** [gember1501/fractals#1]
Je zet de kleuren bij 14, 11, 7 en 5. Maar op het moment dat je het tweede huisje maakt in de tweede generatie staat de kleur dan nog op die je bij 14 of 11  hebt gebruikt.

```
    if aantal == 14:
        t.pencolor('#006666')

    if aantal == 11:
        t.pencolor('#008080')

    if aantal == 7:
        t.pencolor('#66b2b2')

    if aantal == 5:
        t.pencolor('#b2d8d8')

```

**Comment by gember1501** [comment]
is gefixt ik heb de kleuren nu aangepast naar 'lengte' en niet 'aantal'
